
.PHONY: all
all: R56250-boardjpg_zpsd14ef8a2.jpg R56250-serial-connections_zps81203a56.jpg

R56250-boardjpg_zpsd14ef8a2.jpg:
	wget https://i1336.photobucket.com/albums/o646/two2tangle/R56250-boardjpg_zpsd14ef8a2.jpg

R56250-serial-connections_zps81203a56.jpg:
	wget https://i1336.photobucket.com/albums/o646/two2tangle/R56250-serial-connections_zps81203a56.jpg


